# Generated by Django 5.2.6 on 2025-09-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationtask',
            name='optimization_type',
            field=models.CharField(choices=[('schedule', 'Schedule Optimization'), ('route', 'Route Optimization'), ('fuel', 'Fuel Efficiency'), ('multi_objective', 'Multi-Objective'), ('dqn', 'Deep Q-Network (DQN)')], max_length=20),
        ),
    ]
